### ISSUE TITLE
动议: 打包apk之后的路径能否持久化?

### ISSUE THREAD

**Issue by testacount1** [MikaGuraN/HL4A#3]
因为很难从弹窗记得apk的完整路径. 能否将路径文本放在"打包apk"按钮后面, 或者(脑洞)能否有快捷方式跳转到那个apk路径下?

**Comment by MikaGuraN** [comment]
sd卡/HL4A 这很难记得么.....

**Comment by MikaGuraN** [comment]
跳转到路径下不可行，我在弹窗里加上路径吧？

**Comment by nobodxbodon** [comment]
弹窗里好像已经有路径了? 

> sd卡/HL4A 这很难记得么.....

对android文件系统不了解的应该不会知道吧. 另外, 如果没有sd卡, 路径是...?

**Comment by MikaGuraN** [comment]
@nobodxbodon  就是内置存储啊
